import { type TargetStyle } from "@/lib/content/constants";
import { type GlossaryTermDefinition } from "@/lib/content/glossary";

const ALL_TARGET_STYLES: TargetStyle[] = [
  "standard_igbo",
  "code_mixed_igbo_english",
  "child_friendly_igbo",
];

export const APPROVED_GLOSSARY_TERMS: GlossaryTermDefinition[] = [
  {
    term_id: "fraction",
    english: "fraction",
    category: "fraction",
    outputs: {
      standard_igbo: "akụkụ nke ihe zuru ezu",
      code_mixed_igbo_english: "fraction",
      child_friendly_igbo: "fraction, ya bụ akụkụ nke ihe zuru ezu",
    },
    definition_igbo: "akụkụ nke ihe zuru ezu",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 80,
    topic_scope: ["fraction", "fractions"],
    aliases: ["fraction", "fractions"],
    teacher_note:
      "In code-mixed style, keep 'fraction' because learners may meet it in school texts. In child-friendly style, explain it immediately.",
  },
  {
    term_id: "number",
    english: "number",
    category: "general_number",
    outputs: {
      standard_igbo: "ọnụọgụ",
      code_mixed_igbo_english: "number",
      child_friendly_igbo: "ọnụọgụ, ya bụ ihe e ji agụta ma ọ bụ gbakọọ",
    },
    definition_igbo: "ọnụọgụ bụ ihe e ji agụta, atụ ihe, ma ọ bụ gbakọọ",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 20,
    aliases: ["number", "numbers"],
    teacher_note:
      "Use this for the general idea of a number. Do not confuse it with digit.",
  },
  {
    term_id: "digit",
    english: "digit",
    category: "general_number",
    outputs: {
      standard_igbo: "akara ọnụọgụ",
      code_mixed_igbo_english: "digit",
      child_friendly_igbo:
        "digit, ya bụ otu akara e ji dee ọnụọgụ, dịka 0 ruo 9",
    },
    definition_igbo: "digit bụ akara otu n’ime 0 ruo 9 e ji dee ọnụọgụ",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 60,
    aliases: ["digit", "digits"],
    teacher_note:
      "Use digit when referring to one symbol inside a number. Example: in 45, 4 and 5 are digits.",
  },
  {
    term_id: "numerator",
    english: "numerator",
    category: "fraction",
    outputs: {
      standard_igbo: "ọnụọgụ dị n’elu",
      code_mixed_igbo_english: "numerator",
      child_friendly_igbo: "numerator, ya bụ ọnụọgụ dị n’elu na fraction",
    },
    definition_igbo: "ọnụọgụ dị n’elu na fraction",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: ["nọmba elu"],
    status: "approved",
    priority: 100,
    topic_scope: ["fraction", "fractions", "numerator", "denominator"],
    aliases: [
      "numerator",
      "top number",
      "number on top",
      "upper number",
      "number above",
    ],
    teacher_note:
      "For code-mixed style, keep 'numerator' and explain it as the top number in a fraction.",
  },
  {
    term_id: "denominator",
    english: "denominator",
    category: "fraction",
    outputs: {
      standard_igbo: "ọnụọgụ dị n’okpuru",
      code_mixed_igbo_english: "denominator",
      child_friendly_igbo: "denominator, ya bụ ọnụọgụ dị n’okpuru na fraction",
    },
    definition_igbo: "ọnụọgụ dị n’okpuru na fraction",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: ["nọmba ala"],
    status: "approved",
    priority: 100,
    topic_scope: ["fraction", "fractions", "numerator", "denominator"],
    aliases: [
      "denominator",
      "bottom number",
      "number at the bottom",
      "lower number",
      "number below",
    ],
    teacher_note:
      "For code-mixed style, keep 'denominator' and explain it as the bottom number in a fraction.",
  },
  {
    term_id: "equal_parts",
    english: "equal parts",
    category: "fraction",
    outputs: {
      standard_igbo: "akụkụ hà nhata",
      code_mixed_igbo_english: "equal parts",
      child_friendly_igbo:
        "akụkụ hà nhata, ya bụ akụkụ niile hà otu nha",
    },
    definition_igbo: "akụkụ niile nwere otu nha",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: ["akụkụ yiri ibe ha"],
    status: "approved",
    priority: 95,
    topic_scope: ["fraction", "fractions", "equal parts", "shapes"],
    aliases: [
      "equal part",
      "equal parts",
      "same-size part",
      "same-size parts",
      "same size part",
      "same size parts",
      "same-sized part",
      "same-sized parts",
    ],
    teacher_note:
      "Use this when a whole or shape is divided into parts with the same size.",
  },
  {
    term_id: "parts",
    english: "parts",
    category: "fraction",
    outputs: {
      standard_igbo: "akụkụ",
      code_mixed_igbo_english: "parts",
      child_friendly_igbo: "parts, ya bụ akụkụ nke ihe dum",
    },
    definition_igbo: "akụkụ nke ihe dum ma ọ bụ shape",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 45,
    topic_scope: ["fraction", "fractions", "shapes", "equal parts"],
    aliases: ["part", "parts"],
    teacher_note:
      "Use this for pieces or sections. Use equal parts only when the pieces must have the same size.",
  },
  {
    term_id: "decimal",
    english: "decimal",
    category: "decimal",
    outputs: {
      standard_igbo: "ọnụọgụ nwere ntụpọ",
      code_mixed_igbo_english: "decimal",
      child_friendly_igbo: "decimal, ya bụ ọnụọgụ nwere ntụpọ decimal",
    },
    definition_igbo: "ọnụọgụ nwere ntụpọ decimal",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 80,
    topic_scope: ["decimal", "decimals", "fraction", "fractions"],
    aliases: ["decimal", "decimals", "decimal number", "decimal numbers"],
  },
  {
    term_id: "tenths",
    english: "tenths",
    category: "decimal",
    outputs: {
      standard_igbo: "otu ụzọ n’ime iri",
      code_mixed_igbo_english: "tenths",
      child_friendly_igbo: "tenths, ya bụ akụkụ iri nke otu ihe",
    },
    definition_igbo: "akụkụ iri nke otu ihe",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 70,
    topic_scope: ["decimal", "decimals", "place value"],
    aliases: ["tenth", "tenths"],
  },
  {
    term_id: "hundredths",
    english: "hundredths",
    category: "decimal",
    outputs: {
      standard_igbo: "otu ụzọ n’ime otu narị",
      code_mixed_igbo_english: "hundredths",
      child_friendly_igbo: "hundredths, ya bụ akụkụ otu narị nke otu ihe",
    },
    definition_igbo: "akụkụ otu narị nke otu ihe",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 70,
    topic_scope: ["decimal", "decimals", "place value"],
    aliases: ["hundredth", "hundredths"],
  },
  {
    term_id: "place_value",
    english: "place value",
    category: "place_value",
    outputs: {
      standard_igbo: "ọnọdụ ọnụọgụ",
      code_mixed_igbo_english: "place value",
      child_friendly_igbo:
        "place value, ya bụ uru digit nwere dabere n’ebe ọ nọ",
    },
    definition_igbo: "uru digit nwere dabere n’ebe ọ nọ",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 90,
    topic_scope: ["place value", "number", "numeration"],
    aliases: ["place value", "place values"],
  },
  {
    term_id: "rounding",
    english: "rounding",
    category: "place_value",
    outputs: {
      standard_igbo: "ime ka ọnụọgụ dị mfe",
      code_mixed_igbo_english: "rounding",
      child_friendly_igbo:
        "rounding, ya bụ ime ka ọnụọgụ bụrụ nke dị nso ma dị mfe",
    },
    definition_igbo: "ịgbanwe ọnụọgụ ka ọ bụrụ nke dị nso ma dị mfe",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 80,
    topic_scope: ["rounding", "place value"],
    aliases: ["round", "rounds", "rounded", "rounding"],
  },
  {
    term_id: "nearest_thousand",
    english: "nearest thousand",
    category: "place_value",
    outputs: {
      standard_igbo: "puku kacha nso",
      code_mixed_igbo_english: "nearest thousand",
      child_friendly_igbo:
        "nearest thousand, ya bụ puku kacha nso na ọnụọgụ enyere",
    },
    definition_igbo: "puku dị nso na ọnụọgụ enyere",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 95,
    topic_scope: ["rounding", "place value", "thousand"],
    aliases: ["nearest thousand", "nearest thousands"],
  },
  {
    term_id: "thousand",
    english: "thousand",
    category: "place_value",
    outputs: {
      standard_igbo: "puku",
      code_mixed_igbo_english: "thousand",
      child_friendly_igbo: "puku, ya bụ 1000",
    },
    definition_igbo: "ọnụọgụ ruru otu puku",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 40,
    topic_scope: ["place value", "rounding", "large numbers"],
    requires_context: true,
    aliases: ["thousand", "thousands"],
  },
  {
    term_id: "hundred",
    english: "hundred",
    category: "place_value",
    outputs: {
      standard_igbo: "narị",
      code_mixed_igbo_english: "hundred",
      child_friendly_igbo: "narị, ya bụ 100",
    },
    definition_igbo: "ọnụọgụ ruru otu narị",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 40,
    topic_scope: ["place value", "rounding", "large numbers"],
    requires_context: true,
    aliases: ["hundred", "hundreds"],
  },
  {
    term_id: "ones",
    english: "ones",
    category: "place_value",
    outputs: {
      standard_igbo: "ọnọdụ otu",
      code_mixed_igbo_english: "ones",
      child_friendly_igbo: "ones, ya bụ ebe digit otu nọ na ọnụọgụ",
    },
    definition_igbo: "ebe digit otu nọ na ọnụọgụ",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 70,
    topic_scope: ["place value"],
    aliases: ["ones", "units"],
  },
  {
    term_id: "tens",
    english: "tens",
    category: "place_value",
    outputs: {
      standard_igbo: "ọnọdụ iri",
      code_mixed_igbo_english: "tens",
      child_friendly_igbo: "tens, ya bụ ebe digit iri nọ na ọnụọgụ",
    },
    definition_igbo: "ebe digit iri nọ na ọnụọgụ",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 70,
    topic_scope: ["place value"],
    aliases: ["tens"],
  },
  {
    term_id: "shape",
    english: "shape",
    category: "geometry",
    outputs: {
      standard_igbo: "ụdị ihe",
      code_mixed_igbo_english: "shape",
      child_friendly_igbo: "shape, ya bụ ụdị ihe a hụrụ ma ọ bụ sere",
    },
    definition_igbo: "ụdị ihe ma ọ bụ ọdịdị ihe",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 70,
    topic_scope: ["shape", "shapes", "geometry", "fractions"],
    aliases: ["shape", "shapes"],
    teacher_note:
      "Use this for the object or drawing being divided, compared, or named.",
  },
  {
    term_id: "multiply",
    english: "multiply",
    category: "operation",
    outputs: {
      standard_igbo: "mụbaa",
      code_mixed_igbo_english: "mụbaa",
      child_friendly_igbo: "mụbaa, ya bụ ijikọ otu ọnụọgụ ugboro ugboro",
    },
    definition_igbo: "ịjikọta otu ọnụọgụ ugboro ugboro",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 90,
    topic_scope: ["multiplication", "multiply", "operations"],
    aliases: ["multiply", "multiplies", "multiplying", "multiplication"],
  },
  {
    term_id: "add",
    english: "add",
    category: "operation",
    outputs: {
      standard_igbo: "gbakọọ ọnụ",
      code_mixed_igbo_english: "add",
      child_friendly_igbo:
        "gbakọọ ọnụ, ya bụ itinye ọnụọgụ abụọ ma ọ bụ karịa ọnụ",
    },
    definition_igbo: "itinye ọnụọgụ abụọ ma ọ bụ karịa ọnụ",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 80,
    topic_scope: ["addition", "add", "operations"],
    aliases: ["add", "adds", "adding", "addition", "plus"],
  },
  {
    term_id: "subtract",
    english: "subtract",
    category: "operation",
    outputs: {
      standard_igbo: "wepụ",
      code_mixed_igbo_english: "subtract",
      child_friendly_igbo: "wepụ, ya bụ iwepụ otu ọnụọgụ n’ime ọzọ",
    },
    definition_igbo: "iwepụ otu ọnụọgụ n’ime ọzọ",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 80,
    topic_scope: ["subtraction", "subtract", "operations"],
    aliases: ["subtract", "subtracts", "subtracting", "subtraction", "minus"],
  },
  {
    term_id: "divide",
    english: "divide",
    category: "operation",
    outputs: {
      standard_igbo: "kewaa",
      code_mixed_igbo_english: "divide",
      child_friendly_igbo: "kewaa, ya bụ ịkekọrịta ihe n’akụkụ hà nhata",
    },
    definition_igbo: "ịkekọrịta ihe n’akụkụ hà nhata",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 80,
    topic_scope: ["division", "divide", "operations"],
    aliases: ["divide", "divides", "dividing", "division"],
  },
  {
    term_id: "whole",
    english: "whole",
    category: "fraction",
    outputs: {
      standard_igbo: "ihe zuru ezu",
      code_mixed_igbo_english: "whole",
      child_friendly_igbo: "ihe zuru ezu",
    },
    definition_igbo: "ihe zuru ezu nke a na-ekewa n'akụkụ",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 95,
    topic_scope: ["fraction", "fractions"],
    aliases: ["whole", "one whole"],
    teacher_note:
      "Translate as a complete thing or complete amount. Avoid making it sound like a hole.",
  },
  {
    term_id: "half",
    english: "half",
    category: "fraction",
    outputs: {
      standard_igbo: "ọkara",
      code_mixed_igbo_english: "half",
      child_friendly_igbo: "ọkara, otu n'ime akụkụ abụọ hà nhata",
    },
    definition_igbo: "otu n'ime akụkụ abụọ hà nhata",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 95,
    topic_scope: ["fraction", "fractions"],
    aliases: ["half", "one half"],
    teacher_note:
      "In code-mixed style, the English maths term may be kept when it helps learners connect with school textbooks. In child-friendly style, explain the idea simply.",
  },
  {
    term_id: "halves",
    english: "halves",
    category: "fraction",
    outputs: {
      standard_igbo: "ọkara abụọ",
      code_mixed_igbo_english: "halves",
      child_friendly_igbo: "akụkụ abụọ hà nhata",
    },
    definition_igbo: "akụkụ abụọ hà nhata",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 90,
    topic_scope: ["fraction", "fractions"],
    aliases: ["halves"],
    teacher_note: "Use for two equal parts of one whole.",
  },
  {
    term_id: "third",
    english: "third",
    category: "fraction",
    outputs: {
      standard_igbo: "otu n'ime akụkụ atọ hà nhata",
      code_mixed_igbo_english: "third",
      child_friendly_igbo: "otu akụkụ n'ime atọ",
    },
    definition_igbo: "otu n'ime akụkụ atọ hà nhata",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 88,
    topic_scope: ["fraction", "fractions"],
    aliases: ["third", "one third"],
    teacher_note:
      "In code-mixed style, the English maths term may be kept when it helps learners connect with school textbooks. In child-friendly style, explain the idea simply.",
  },
  {
    term_id: "thirds",
    english: "thirds",
    category: "fraction",
    outputs: {
      standard_igbo: "akụkụ atọ hà nhata",
      code_mixed_igbo_english: "thirds",
      child_friendly_igbo: "akụkụ atọ hà otu nha",
    },
    definition_igbo: "akụkụ atọ hà nhata",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 84,
    topic_scope: ["fraction", "fractions"],
    aliases: ["thirds"],
    teacher_note:
      "In code-mixed style, the English maths term may be kept when it helps learners connect with school textbooks. In child-friendly style, explain the idea simply.",
  },
  {
    term_id: "quarter",
    english: "quarter",
    category: "fraction",
    outputs: {
      standard_igbo: "otu n'ime akụkụ anọ hà nhata",
      code_mixed_igbo_english: "quarter",
      child_friendly_igbo: "otu akụkụ n'ime anọ",
    },
    definition_igbo: "otu n'ime akụkụ anọ hà nhata",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 88,
    topic_scope: ["fraction", "fractions"],
    aliases: ["quarter", "one quarter"],
    teacher_note:
      "In code-mixed style, the English maths term may be kept when it helps learners connect with school textbooks. In child-friendly style, explain the idea simply.",
  },
  {
    term_id: "quarters",
    english: "quarters",
    category: "fraction",
    outputs: {
      standard_igbo: "akụkụ anọ hà nhata",
      code_mixed_igbo_english: "quarters",
      child_friendly_igbo: "akụkụ anọ hà otu nha",
    },
    definition_igbo: "akụkụ anọ hà nhata",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 84,
    topic_scope: ["fraction", "fractions"],
    aliases: ["quarters"],
    teacher_note:
      "In code-mixed style, the English maths term may be kept when it helps learners connect with school textbooks. In child-friendly style, explain the idea simply.",
  },
  {
    term_id: "unit_fraction",
    english: "unit fraction",
    category: "fraction",
    outputs: {
      standard_igbo: "fraction nwere ọnụọgụ dị n'elu bụ 1",
      code_mixed_igbo_english: "unit fraction",
      child_friendly_igbo: "fraction nwere 1 n'elu",
    },
    definition_igbo: "fraction nke numerator ya bụ 1",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 92,
    topic_scope: ["fraction", "fractions"],
    aliases: ["unit fraction"],
    teacher_note:
      "In code-mixed style, the English maths term may be kept when it helps learners connect with school textbooks. In child-friendly style, explain the idea simply.",
  },
  {
    term_id: "non_unit_fraction",
    english: "non-unit fraction",
    category: "fraction",
    outputs: {
      standard_igbo: "fraction nke ọnụọgụ dị n'elu karịrị 1",
      code_mixed_igbo_english: "non-unit fraction",
      child_friendly_igbo: "fraction nwere karịa 1 n'elu",
    },
    definition_igbo: "fraction nke numerator ya karịrị 1",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 86,
    topic_scope: ["fraction", "fractions"],
    aliases: ["non-unit fraction", "non unit fraction"],
    teacher_note:
      "In code-mixed style, the English maths term may be kept when it helps learners connect with school textbooks. In child-friendly style, explain the idea simply.",
  },
  {
    term_id: "proper_fraction",
    english: "proper fraction",
    category: "fraction",
    outputs: {
      standard_igbo: "fraction ziri ezi",
      code_mixed_igbo_english: "proper fraction",
      child_friendly_igbo: "fraction nke nọmba elu pere mpe karịa nke ala",
    },
    definition_igbo: "fraction nke numerator pere mpe karịa denominator",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 98,
    topic_scope: ["fraction", "fractions"],
    aliases: ["proper fraction"],
    teacher_note:
      "Explain by saying the top number is smaller than the bottom number.",
  },
  {
    term_id: "improper_fraction",
    english: "improper fraction",
    category: "fraction",
    outputs: {
      standard_igbo: "fraction na-ezighị ezi",
      code_mixed_igbo_english: "improper fraction",
      child_friendly_igbo: "fraction nke nọmba elu hà ma ọ bụ karịrị nke ala",
    },
    definition_igbo: "fraction nke numerator hà ma ọ bụ karịrị denominator",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 98,
    topic_scope: ["fraction", "fractions"],
    aliases: ["improper fraction"],
    teacher_note:
      "Use a clear explanation because the literal phrase may sound negative to children.",
  },
  {
    term_id: "mixed_number",
    english: "mixed number",
    category: "fraction",
    outputs: {
      standard_igbo: "nọmba agwakọtara",
      code_mixed_igbo_english: "mixed number",
      child_friendly_igbo: "nọmba zuru ezu na fraction ọnụ",
    },
    definition_igbo: "nọmba nwere whole number na fraction",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 98,
    topic_scope: ["fraction", "fractions"],
    aliases: ["mixed number", "mixed fraction"],
    teacher_note: "Explain as a whole number and a fraction together.",
  },
  {
    term_id: "equivalent_fraction",
    english: "equivalent fraction",
    category: "fraction",
    outputs: {
      standard_igbo: "fractions hà otu uru",
      code_mixed_igbo_english: "equivalent fraction",
      child_friendly_igbo: "fractions dị iche mana ha hà otu",
    },
    definition_igbo: "fractions nwere otu uru",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 99,
    topic_scope: ["fraction", "fractions"],
    aliases: ["equivalent fraction", "equivalent fractions"],
    teacher_note:
      "Keep equivalent fraction in code-mixed style if useful, then explain same value.",
  },
  {
    term_id: "simplest_form",
    english: "simplest form",
    category: "fraction",
    outputs: {
      standard_igbo: "ụdị kachasị mfe",
      code_mixed_igbo_english: "simplest form",
      child_friendly_igbo: "ụdị kacha mfe",
    },
    definition_igbo: "ụdị fraction a na-apụghị ime ka ọ dị mfe ọzọ",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 90,
    topic_scope: ["fraction", "fractions"],
    aliases: ["simplest form", "lowest form"],
    teacher_note:
      "In code-mixed style, the English maths term may be kept when it helps learners connect with school textbooks. In child-friendly style, explain the idea simply.",
  },
  {
    term_id: "simplify",
    english: "simplify",
    category: "fraction",
    outputs: {
      standard_igbo: "mee ka ọ dị mfe",
      code_mixed_igbo_english: "simplify",
      child_friendly_igbo: "mee fraction ka ọ dị mfe",
    },
    definition_igbo: "ịkewa numerator na denominator site n'otu factor iji nweta ụdị mfe",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 89,
    topic_scope: ["fraction", "fractions"],
    aliases: ["simplify", "simplifying"],
    teacher_note:
      "In code-mixed style, the English maths term may be kept when it helps learners connect with school textbooks. In child-friendly style, explain the idea simply.",
  },
  {
    term_id: "compare_fractions",
    english: "compare fractions",
    category: "fraction",
    outputs: {
      standard_igbo: "tụnyere fractions",
      code_mixed_igbo_english: "compare fractions",
      child_friendly_igbo: "lee fraction nke ka ibu ma ọ bụ ka nta",
    },
    definition_igbo: "ịtụnyere fractions iji mata nke ka ukwuu ma ọ bụ nke ka nta",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 88,
    topic_scope: ["fraction", "fractions"],
    aliases: ["compare fractions", "comparing fractions"],
    teacher_note:
      "In code-mixed style, the English maths term may be kept when it helps learners connect with school textbooks. In child-friendly style, explain the idea simply.",
  },
  {
    term_id: "order_fractions",
    english: "order fractions",
    category: "fraction",
    outputs: {
      standard_igbo: "hazie fractions n'usoro",
      code_mixed_igbo_english: "order fractions",
      child_friendly_igbo: "tinye fractions n'usoro",
    },
    definition_igbo: "ịhazie fractions site n'obere ruo nnukwu ma ọ bụ site na nnukwu ruo obere",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 86,
    topic_scope: ["fraction", "fractions"],
    aliases: ["order fractions", "ordering fractions"],
    teacher_note:
      "In code-mixed style, the English maths term may be kept when it helps learners connect with school textbooks. In child-friendly style, explain the idea simply.",
  },
  {
    term_id: "ascending_order",
    english: "ascending order",
    category: "fraction",
    outputs: {
      standard_igbo: "usoro site n'obere gaa na nnukwu",
      code_mixed_igbo_english: "ascending order",
      child_friendly_igbo: "obere gaa na nnukwu",
    },
    definition_igbo: "usoro na-amalite n'obere wee ruo nnukwu",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 84,
    topic_scope: ["fraction", "fractions"],
    aliases: ["ascending order"],
    teacher_note:
      "In code-mixed style, the English maths term may be kept when it helps learners connect with school textbooks. In child-friendly style, explain the idea simply.",
  },
  {
    term_id: "descending_order",
    english: "descending order",
    category: "fraction",
    outputs: {
      standard_igbo: "usoro site na nnukwu gaa n'obere",
      code_mixed_igbo_english: "descending order",
      child_friendly_igbo: "nnukwu gaa n'obere",
    },
    definition_igbo: "usoro na-amalite na nnukwu wee ruo obere",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 84,
    topic_scope: ["fraction", "fractions"],
    aliases: ["descending order"],
    teacher_note:
      "In code-mixed style, the English maths term may be kept when it helps learners connect with school textbooks. In child-friendly style, explain the idea simply.",
  },
  {
    term_id: "common_denominator",
    english: "common denominator",
    category: "fraction",
    outputs: {
      standard_igbo: "denominator jikọrọ ọnụ",
      code_mixed_igbo_english: "common denominator",
      child_friendly_igbo: "otu bottom number maka fractions",
    },
    definition_igbo: "otu denominator a na-eji maka fractions abụọ ma ọ bụ karịa",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 93,
    topic_scope: ["fraction", "fractions"],
    aliases: ["common denominator"],
    teacher_note:
      "In code-mixed style, the English maths term may be kept when it helps learners connect with school textbooks. In child-friendly style, explain the idea simply.",
  },
  {
    term_id: "least_common_denominator",
    english: "least common denominator",
    category: "fraction",
    outputs: {
      standard_igbo: "denominator jikọrọ ọnụ kacha nta",
      code_mixed_igbo_english: "least common denominator",
      child_friendly_igbo: "bottom number kacha nta nke fractions nwere ike iji ọnụ",
    },
    definition_igbo: "denominator jikọrọ ọnụ kacha nta",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 92,
    topic_scope: ["fraction", "fractions"],
    aliases: ["least common denominator", "lcd"],
    teacher_note:
      "In code-mixed style, the English maths term may be kept when it helps learners connect with school textbooks. In child-friendly style, explain the idea simply.",
  },
  {
    term_id: "multiple",
    english: "multiple",
    category: "number",
    outputs: {
      standard_igbo: "mụltịpụlụ",
      code_mixed_igbo_english: "multiple",
      child_friendly_igbo: "nsonaazụ ịmụba nọmba",
    },
    definition_igbo: "nsonaazụ nke ịmụba ọnụọgụ site na ọnụọgụ ndị ọzọ",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 72,
    topic_scope: ["fraction", "fractions"],
    aliases: ["multiple", "multiples"],
    teacher_note:
      "In code-mixed style, the English maths term may be kept when it helps learners connect with school textbooks. In child-friendly style, explain the idea simply.",
  },
  {
    term_id: "factor",
    english: "factor",
    category: "number",
    outputs: {
      standard_igbo: "factor",
      code_mixed_igbo_english: "factor",
      child_friendly_igbo: "nọmba na-ekewa nọmba ọzọ kpọmkwem",
    },
    definition_igbo: "ọnụọgụ na-ekewa ọnụọgụ ọzọ na-enweghị remainder",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 72,
    topic_scope: ["fraction", "fractions"],
    aliases: ["factor", "factors"],
    teacher_note:
      "In code-mixed style, the English maths term may be kept when it helps learners connect with school textbooks. In child-friendly style, explain the idea simply.",
  },
  {
    term_id: "lowest_common_multiple",
    english: "lowest common multiple",
    category: "number",
    outputs: {
      standard_igbo: "mụltịpụlụ jikọrọ ọnụ kacha nta",
      code_mixed_igbo_english: "lowest common multiple",
      child_friendly_igbo: "LCM, nọmba kacha nta ha nwere ọnụ",
    },
    definition_igbo: "mụltịpụlụ kacha nta nke ọnụọgụ abụọ ma ọ bụ karịa nwere ọnụ",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 78,
    topic_scope: ["fraction", "fractions"],
    aliases: ["lowest common multiple", "least common multiple", "LCM"],
    teacher_note:
      "In code-mixed style, the English maths term may be kept when it helps learners connect with school textbooks. In child-friendly style, explain the idea simply.",
  },
  {
    term_id: "add_fractions",
    english: "add fractions",
    category: "fraction",
    outputs: {
      standard_igbo: "gbakọọ fractions ọnụ",
      code_mixed_igbo_english: "add fractions",
      child_friendly_igbo: "tinye fractions ọnụ",
    },
    definition_igbo: "ịgbakọta fractions abụọ ma ọ bụ karịa",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 88,
    topic_scope: ["fraction", "fractions"],
    aliases: ["add fractions", "adding fractions"],
    teacher_note:
      "In code-mixed style, the English maths term may be kept when it helps learners connect with school textbooks. In child-friendly style, explain the idea simply.",
  },
  {
    term_id: "subtract_fractions",
    english: "subtract fractions",
    category: "fraction",
    outputs: {
      standard_igbo: "wepụ fractions",
      code_mixed_igbo_english: "subtract fractions",
      child_friendly_igbo: "wepụ otu fraction n'otu ọzọ",
    },
    definition_igbo: "iwepụ fraction site na fraction ọzọ",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 88,
    topic_scope: ["fraction", "fractions"],
    aliases: ["subtract fractions", "subtracting fractions"],
    teacher_note:
      "In code-mixed style, the English maths term may be kept when it helps learners connect with school textbooks. In child-friendly style, explain the idea simply.",
  },
  {
    term_id: "multiply_fractions",
    english: "multiply fractions",
    category: "fraction",
    outputs: {
      standard_igbo: "mụbaa fractions",
      code_mixed_igbo_english: "multiply fractions",
      child_friendly_igbo: "mụbaa fractions ọnụ",
    },
    definition_igbo: "ịmụba numerator na numerator, denominator na denominator",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 90,
    topic_scope: ["fraction", "fractions"],
    aliases: ["multiply fractions", "multiplying fractions"],
    teacher_note:
      "In code-mixed style, the English maths term may be kept when it helps learners connect with school textbooks. In child-friendly style, explain the idea simply.",
  },
  {
    term_id: "divide_fractions",
    english: "divide fractions",
    category: "fraction",
    outputs: {
      standard_igbo: "kee fractions",
      code_mixed_igbo_english: "divide fractions",
      child_friendly_igbo: "kee fractions site n'ịtụgharị nke abụọ",
    },
    definition_igbo: "ịkekọrịta fractions site n'iji reciprocal",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 90,
    topic_scope: ["fraction", "fractions"],
    aliases: ["divide fractions", "dividing fractions"],
    teacher_note:
      "In code-mixed style, the English maths term may be kept when it helps learners connect with school textbooks. In child-friendly style, explain the idea simply.",
  },
  {
    term_id: "reciprocal",
    english: "reciprocal",
    category: "fraction",
    outputs: {
      standard_igbo: "fraction a tụgharịrị elu na ala",
      code_mixed_igbo_english: "reciprocal",
      child_friendly_igbo: "tụgharịa fraction elu na ala",
    },
    definition_igbo: "fraction a na-enweta site n'ịgbanwe numerator na denominator",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 86,
    topic_scope: ["fraction", "fractions"],
    aliases: ["reciprocal"],
    teacher_note: "In code-mixed style, keep reciprocal and explain as flipping the fraction.",
  },
  {
    term_id: "fraction_of_a_number",
    english: "fraction of a number",
    category: "fraction",
    outputs: {
      standard_igbo: "akụkụ nke ọnụọgụ",
      code_mixed_igbo_english: "fraction of a number",
      child_friendly_igbo: "akụkụ nke group ma ọ bụ number",
    },
    definition_igbo: "iji fraction chọta akụkụ nke ọnụọgụ",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 89,
    topic_scope: ["fraction", "fractions"],
    aliases: ["fraction of a number", "fraction of a quantity"],
    teacher_note:
      "In code-mixed style, the English maths term may be kept when it helps learners connect with school textbooks. In child-friendly style, explain the idea simply.",
  },
  {
    term_id: "shaded_part",
    english: "shaded part",
    category: "fraction",
    outputs: {
      standard_igbo: "akụkụ e sere agba",
      code_mixed_igbo_english: "shaded part",
      child_friendly_igbo: "akụkụ e tinyere agba",
    },
    definition_igbo: "akụkụ nke eserela agba ma ọ bụ akara",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 76,
    topic_scope: ["fraction", "fractions"],
    aliases: ["shaded part", "shaded parts"],
    teacher_note:
      "In code-mixed style, the English maths term may be kept when it helps learners connect with school textbooks. In child-friendly style, explain the idea simply.",
  },
  {
    term_id: "unshaded_part",
    english: "unshaded part",
    category: "fraction",
    outputs: {
      standard_igbo: "akụkụ a na-eseghị agba",
      code_mixed_igbo_english: "unshaded part",
      child_friendly_igbo: "akụkụ enweghị agba",
    },
    definition_igbo: "akụkụ nke a na-eseghị agba ma ọ bụ akara",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 74,
    topic_scope: ["fraction", "fractions"],
    aliases: ["unshaded part", "unshaded parts"],
    teacher_note:
      "In code-mixed style, the English maths term may be kept when it helps learners connect with school textbooks. In child-friendly style, explain the idea simply.",
  },
  {
    term_id: "percentage",
    english: "percentage",
    category: "percentage",
    outputs: {
      standard_igbo: "pasent",
      code_mixed_igbo_english: "percentage",
      child_friendly_igbo: "pasent, ya bụ out of 100",
    },
    definition_igbo: "ọnụọgụ e gosiri dịka akụkụ n'ime 100",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 76,
    topic_scope: ["fraction", "fractions"],
    aliases: ["percentage", "percent", "per cent"],
    teacher_note:
      "In code-mixed style, the English maths term may be kept when it helps learners connect with school textbooks. In child-friendly style, explain the idea simply.",
  },
  {
    term_id: "word_problem",
    english: "word problem",
    category: "problem_solving",
    outputs: {
      standard_igbo: "ajụjụ akụkọ",
      code_mixed_igbo_english: "word problem",
      child_friendly_igbo: "ajụjụ maths dị ka akụkọ",
    },
    definition_igbo: "ajụjụ mgbakọ na mwepụ e dere n'ụdị akụkọ",
    allowed_styles: ALL_TARGET_STYLES,
    forbidden_translations: [],
    status: "approved",
    priority: 70,
    topic_scope: ["fraction", "fractions"],
    aliases: ["word problem", "story problem"],
    teacher_note:
      "In code-mixed style, the English maths term may be kept when it helps learners connect with school textbooks. In child-friendly style, explain the idea simply.",
  },
];
